### PR TITLE
Retry creation scripts up to 3 times before failing.

### LINKED ISSUE #168: Cluster destruction fails if one of the helm charts is not installed.
I started to tear down a cluster but had deleted the `benchmarking` pod from helm.

Now, my cluster is in a retry loop trying to delete a pod that is not installed.

Screen Shot 2019-08-07 at 10 34 11 AM

Additionally, if I cancel out of this retry loop, I can no longer DELETE my cluster.

Screen Shot 2019-08-07 at 10 36 11 AM

### PR DESCRIPTION
**Pull request by willgraf**
This PR uses a for loop to deploy (and destroy) helmfiles and node-pools.  This fixes #168  by preventing the infinite retry loop. Additionally, it has updated the node-pool destruction to destroy all custom node-pools without hard-coding the name.

### CODE REVIEW

File: conf/patches/gke-helmfile-deployment.sh [hunk 1]
```diff
@@ -1,9 +1,12 @@
...
+
 for filename in /conf/helmfile.d/*.yaml; do
-    echo ${filename}
-    #echo 'grep "\- name: " ${filename} | grep -m1 -v "\- name: \"stable\"" | awk {print \$3} | sed s/^\"\(.\+\)\"$/\1/'
     deployment_name=$(grep "\- name: " ${filename} | grep -m1 -v "\- name: \"stable\"" | awk '{print $3}' | sed 's/^\"\(.\+\)\"$/\1/')
-    echo ${deployment_name}
-    until helmfile --selector name=${deployment_name} sync; do
+    retries=3
+    for ((i=0; i<retries; i++)); do
+        helmfile --selector name=${deployment_name} sync
```
Comment (osterman) [inline conf/patches/gke-helmfile-deployment.sh]: Instead, consider the retry command that ships with geodesic.

Comment (osterman) [reply conf/patches/gke-helmfile-deployment.sh]: https://github.com/kamilsk/retry

Comment (willgraf) [reply conf/patches/gke-helmfile-deployment.sh]: Oh, that looks nice! I'll check this out.
